Revert "kbuild: Add option to turn incompatible pointer check into error"
This reverts commit ea8daa7b97842aab8507b5b5b1e3226cf2d514a6.

This commit caused the following error to occur during build.  Since
we're not necessarily developing a driver here at Zen Kernel sources,
lets just turn it back off.  In fact, on February 19th, Ingo reverted
this change just to have Daniel Wagner enable it again.

  CC [M]  drivers/char/lp.o
drivers/char/lp.c:823:12: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .write  = lp_console_write,
            ^
drivers/char/lp.c:823:12: note: (near initialization for ‘lpcons.write’)