add ifdefs to handle CONFIG_FREEZER properly
This commit fixes the following compilation issues, discovered by
pf-kernel users that do not use hibernation:

===
drivers/md/md.c: In function ‘md_check_recovery’:
drivers/md/md.c:7509:26: error: ‘system_freezing_cnt’ undeclared (first
		use in this function)
drivers/md/md.c:7509:26: note: each undeclared identifier is reported
only once for each function it appears in
===

and

===
CC      mm/vmscan.o
mm/vmscan.c: В функции «do_try_to_free_pages»:
mm/vmscan.c:2376:7: ошибка: «pm_freezing» undeclared (first use in
		this function)
mm/vmscan.c:2376:7: замечание: each undeclared identifier is reported
only once for each function it appears in
mm/vmscan.c: В функции «wakeup_kswapd»:
mm/vmscan.c:3149:6: ошибка: «pm_freezing» undeclared (first use in
		this function)
make[1]: *** [mm/vmscan.o] Ошибка 1
make: *** [mm] Ошибка 2
===

Conflicts:

	mm/vmscan.c