Revert "add scheduler turbo3 patch"
This reverts commit 413d025caeea77b53769eec5560c4cd583e5b0b9.

Fails to build:

ld: arch/x86/kernel/itmt.o: in function `sched_set_itmt_core_prio':
itmt.c:(.text+0x20f): undefined reference to `best_core'
ld: itmt.c:(.text+0x225): undefined reference to `second_best_core'